---
- include: install.yml
  tags:
    - install

- include: config.yml
  tags:
    - config

- include: database.yml
  tags:
    - database
  when: mattermost_database_host == 'localhost' and mattermost_database_create and mattermost_database_driver == 'postgres'

- name: Start and enable mattermost
  service:
    name: mattermost
    state: started
    enabled: true
